spring:
  security:
    saml2:
      relyingparty:
        registration:
          JavaWebAppSSO:
            identityprovider:
              entity-id: 2afa2000-7726-4920-a957-0397c340fc3d
              client-id: c4187447-d544-404d-8440-49de0d869d75
              verification.credentials:
                #need to add RSA key as well
                #- private-key-location: "classpath:credentials/azure.key"
                - certificate-location: "classpath:credentials/azure.crt"
              singlesignon.url: https://login.microsoftonline.com/2afa2000-7726-4920-a957-0397c340fc3d/saml2
              #change to true when RSA key added
              singlesignon.sign-request: false